---
{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kayenta.fullname" . }}
  labels:
    {{- include "kayenta.labels" . | nindent 4}}
type: {{ .Values.secret.type }}
data:
{{- range $key, $val := .Values.secret.data }}
  {{ $key | nindent 2 }}: {{ $val | quote | b64enc }}
{{- end }}
{{- end }}